# Generated by Django 4.1 on 2022-09-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_alter_uploadfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='ImageFiles'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='title',
            field=models.CharField(blank=True, default='New Document', max_length=100),
        ),
    ]
