# Generated by Django 4.1 on 2022-09-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_alter_uploadfile_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='thumb',
            field=models.FileField(upload_to='ImageFiles'),
        ),
    ]
