# Generated by Django 4.1 on 2022-09-28 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_rename_thumb_uploadfile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 22, 39, 1, 215596)),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
